[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "web-scraper"
version = "0.1.0"
description = "Web scraping project"
requires-python = ">=3.8"
dependencies = [
    "playwright",
    "asyncio",
]

[tool.setuptools]
packages = ["lib"] 